name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  animated_text_kit: ^2.0.0
  firebase_core: ^0.4.4
  firebase_auth: ^0.15.4
  cloud_firestore: ^0.13.3
  responsive_grid: ^1.1.1
  modal_progress_hud: ^0.1.3
  carousel_pro: ^1.0.0
  google_sign_in: ^4.1.4

  shared_preferences: ^0.5.6+2
  intl: ^0.15.8
  fluttertoast: ^7.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/
  - caraimages/
  - cara/
